PERIPHERALS = pit extint
DRIVERS = button led pacer usb_serial panic adxl345 adxl_data nrf24 radio_freq radio_funct radio_hat radio_sm_hat circ_buff buzzer music ledtape ledstrip battery_monitor
SRC = hat.c

# Use low level of optimisation to simplify debugging
OPT = -O1

BOARD = hat

include ../../boards/board.mk
