PERIPHERALS = pit extint
# DRIVERS = button led pacer usb_serial panic nrf24 radio_freq motors radio_funct motor_radio

DRIVERS = button led pacer usb_serial panic nrf24 radio_freq motors motor_radio radio_funct circ_buff radio_sm_racer battery_monitor bumper ledtape ledstrip battery_monitor
# SRC = racer.c
SRC = racer.c

# Use low level of optimisation to simplify debugging
OPT = -O1

# BOARD = racer 

include ../../boards/board.mk
